//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//

//@javax.xml.bind.annotation.XmlSchema(xmlns = {
//        @javax.xml.bind.annotation.XmlNs(prefix = "taf",
//                namespaceURI="http://taf-jsg.info/schemes")})

//@javax.xml.bind.annotation.XmlSchema(
//    namespace="http://taf-jsg.info/schemes",
//    xmlns={@javax.xml.bind.annotation.XmlNs(prefix="taf",
//                  namespaceURI="http://taf-jsg.info/schemes")}
//)

@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://taf-jsg.info/schemes", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, 
		xmlns = { 
				@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://taf-jsg.info/schemes", 
						prefix = "") 
		}
)
package info.taf_jsg.schemes;
