//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonNumberFreight"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonTrainPosition"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonOperationalData"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonTechData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "wagonNumberFreight",
        "wagonTrainPosition",
        "wagonOperationalData",
        "wagonTechData"
})
@XmlRootElement(name = "WagonData")
public class WagonData {

    @XmlElement(name = "WagonNumberFreight", required = true)
    protected String wagonNumberFreight;
    @XmlElement(name = "WagonTrainPosition")
    protected int wagonTrainPosition;
    @XmlElement(name = "WagonOperationalData", required = true)
    protected WagonOperationalData wagonOperationalData;
    @XmlElement(name = "WagonTechData", required = true)
    protected WagonTechData wagonTechData;

    /**
     * Gets the value of the wagonNumberFreight property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getWagonNumberFreight() {
        return wagonNumberFreight;
    }

    public WagonData setWagonNumberFreight(String wagonNumberFreight) {
        this.wagonNumberFreight = wagonNumberFreight;
        return this;
    }

    /**
     * Gets the value of the wagonTrainPosition property.
     */
    public int getWagonTrainPosition() {
        return wagonTrainPosition;
    }

    public WagonData setWagonTrainPosition(int wagonTrainPosition) {
        this.wagonTrainPosition = wagonTrainPosition;
        return this;
    }

    /**
     * Gets the value of the wagonOperationalData property.
     *
     * @return possible object is
     * {@link WagonOperationalData }
     */
    public WagonOperationalData getWagonOperationalData() {
        return wagonOperationalData;
    }

    public WagonData setWagonOperationalData(WagonOperationalData wagonOperationalData) {
        this.wagonOperationalData = wagonOperationalData;
        return this;
    }

    /**
     * Gets the value of the wagonTechData property.
     *
     * @return possible object is
     * {@link WagonTechData }
     */
    public WagonTechData getWagonTechData() {
        return wagonTechData;
    }

    public WagonData setWagonTechData(WagonTechData wagonTechData) {
        this.wagonTechData = wagonTechData;
        return this;
    }
}
