//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}BrakeType" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}BrakeWeight" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonMaxSpeed" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ExceptionalGaugingProfile" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ExceptionalGaugingIdent" minOccurs="0"/>
 *         &lt;element name="DangerousGoodsDetails" maxOccurs="99" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}DangerousGoodsIndication" minOccurs="0"/>
 *                   &lt;element name="WeightOfDangerousGoods" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="999999"/>
 *                         &lt;totalDigits value="6"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}InfoOnGoodsShapeTypeDanger" maxOccurs="9" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}RestrictionsDueToLoadOrDamage" maxOccurs="9" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TotalLoadWeight" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "brakeType",
        "brakeWeight",
        "wagonMaxSpeed",
        "exceptionalGaugingProfile",
        "exceptionalGaugingIdent",
        "dangerousGoodsDetails",
        "infoOnGoodsShapeTypeDanger",
        "restrictionsDueToLoadOrDamage",
        "totalLoadWeight"
})
@XmlRootElement(name = "WagonOperationalData")
public class WagonOperationalData {

    @XmlElement(name = "BrakeType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String brakeType;
    @XmlElement(name = "BrakeWeight")
    protected Integer brakeWeight;
    @XmlElement(name = "WagonMaxSpeed")
    protected Integer wagonMaxSpeed;
    @XmlElement(name = "ExceptionalGaugingProfile")
    protected String exceptionalGaugingProfile;
    @XmlElement(name = "ExceptionalGaugingIdent")
    protected ExceptionalGaugingIdent exceptionalGaugingIdent;
    @XmlElement(name = "DangerousGoodsDetails")
    protected List<WagonOperationalData.DangerousGoodsDetails> dangerousGoodsDetails;
    @XmlElement(name = "InfoOnGoodsShapeTypeDanger")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected List<String> infoOnGoodsShapeTypeDanger;
    @XmlElement(name = "RestrictionsDueToLoadOrDamage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected List<String> restrictionsDueToLoadOrDamage;
    @XmlElement(name = "TotalLoadWeight")
    protected Integer totalLoadWeight;

    /**
     * Gets the value of the brakeType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBrakeType() {
        return brakeType;
    }

    public WagonOperationalData setBrakeType(String brakeType) {
        this.brakeType = brakeType;
        return this;
    }

    /**
     * Gets the value of the brakeWeight property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getBrakeWeight() {
        return brakeWeight;
    }

    public WagonOperationalData setBrakeWeight(Integer brakeWeight) {
        this.brakeWeight = brakeWeight;
        return this;
    }

    /**
     * Gets the value of the wagonMaxSpeed property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getWagonMaxSpeed() {
        return wagonMaxSpeed;
    }

    public WagonOperationalData setWagonMaxSpeed(Integer wagonMaxSpeed) {
        this.wagonMaxSpeed = wagonMaxSpeed;
        return this;
    }

    /**
     * Gets the value of the exceptionalGaugingProfile property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExceptionalGaugingProfile() {
        return exceptionalGaugingProfile;
    }

    public WagonOperationalData setExceptionalGaugingProfile(String exceptionalGaugingProfile) {
        this.exceptionalGaugingProfile = exceptionalGaugingProfile;
        return this;
    }

    /**
     * Gets the value of the exceptionalGaugingIdent property.
     *
     * @return possible object is
     * {@link ExceptionalGaugingIdent }
     */
    public ExceptionalGaugingIdent getExceptionalGaugingIdent() {
        return exceptionalGaugingIdent;
    }

    public WagonOperationalData setExceptionalGaugingIdent(ExceptionalGaugingIdent exceptionalGaugingIdent) {
        this.exceptionalGaugingIdent = exceptionalGaugingIdent;
        return this;
    }

    /**
     * Gets the value of the dangerousGoodsDetails property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dangerousGoodsDetails property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDangerousGoodsDetails().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WagonOperationalData.DangerousGoodsDetails }
     */
    public List<WagonOperationalData.DangerousGoodsDetails> getDangerousGoodsDetails() {
        if (dangerousGoodsDetails == null) {
            dangerousGoodsDetails = new ArrayList<WagonOperationalData.DangerousGoodsDetails>();
        }
        return this.dangerousGoodsDetails;
    }

    public WagonOperationalData setDangerousGoodsDetails(List<DangerousGoodsDetails> dangerousGoodsDetails) {
        this.dangerousGoodsDetails = dangerousGoodsDetails;
        return this;
    }

    public WagonOperationalData addDangerGoodsDetails(DangerousGoodsDetails dangerousGoodsDetails) {
        if (this.dangerousGoodsDetails == null) {
            this.dangerousGoodsDetails = new ArrayList<>();
        }
        this.dangerousGoodsDetails.add(dangerousGoodsDetails);
        return this;
    }

    /**
     * Gets the value of the infoOnGoodsShapeTypeDanger property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infoOnGoodsShapeTypeDanger property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfoOnGoodsShapeTypeDanger().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getInfoOnGoodsShapeTypeDanger() {
        if (infoOnGoodsShapeTypeDanger == null) {
            infoOnGoodsShapeTypeDanger = new ArrayList<String>();
        }
        return this.infoOnGoodsShapeTypeDanger;
    }

    public WagonOperationalData setInfoOnGoodsShapeTypeDanger(List<String> infoOnGoodsShapeTypeDanger) {
        this.infoOnGoodsShapeTypeDanger = infoOnGoodsShapeTypeDanger;
        return this;
    }

    /**
     * Gets the value of the restrictionsDueToLoadOrDamage property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restrictionsDueToLoadOrDamage property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestrictionsDueToLoadOrDamage().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getRestrictionsDueToLoadOrDamage() {
        if (restrictionsDueToLoadOrDamage == null) {
            restrictionsDueToLoadOrDamage = new ArrayList<String>();
        }
        return this.restrictionsDueToLoadOrDamage;
    }

    public WagonOperationalData setRestrictionsDueToLoadOrDamage(List<String> restrictionsDueToLoadOrDamage) {
        this.restrictionsDueToLoadOrDamage = restrictionsDueToLoadOrDamage;
        return this;
    }

    /**
     * Gets the value of the totalLoadWeight property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getTotalLoadWeight() {
        return totalLoadWeight;
    }

    public WagonOperationalData setTotalLoadWeight(Integer totalLoadWeight) {
        this.totalLoadWeight = totalLoadWeight;
        return this;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://taf-jsg.info/schemes}DangerousGoodsIndication" minOccurs="0"/>
     *         &lt;element name="WeightOfDangerousGoods" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="999999"/>
     *               &lt;totalDigits value="6"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "dangerousGoodsIndication",
            "weightOfDangerousGoods"
    })
    public static class DangerousGoodsDetails {

        @XmlElement(name = "DangerousGoodsIndication")
        protected DanGoodsType dangerousGoodsIndication;
        @XmlElement(name = "WeightOfDangerousGoods")
        protected BigDecimal weightOfDangerousGoods;

        /**
         * Gets the value of the dangerousGoodsIndication property.
         *
         * @return possible object is
         * {@link DanGoodsType }
         */
        public DanGoodsType getDangerousGoodsIndication() {
            return dangerousGoodsIndication;
        }

        public DangerousGoodsDetails setDangerousGoodsIndication(DanGoodsType dangerousGoodsIndication) {
            this.dangerousGoodsIndication = dangerousGoodsIndication;
            return this;
        }

        /**
         * Gets the value of the weightOfDangerousGoods property.
         *
         * @return possible object is
         * {@link BigDecimal }
         */
        public BigDecimal getWeightOfDangerousGoods() {
            return weightOfDangerousGoods;
        }

        public DangerousGoodsDetails setWeightOfDangerousGoods(BigDecimal weightOfDangerousGoods) {
            this.weightOfDangerousGoods = weightOfDangerousGoods;
            return this;
        }
    }

}
