//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LengthOverBuffers"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonNumberOfAxles"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}AirBrakeType" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}BrakingPowerVariationDevice" minOccurs="0"/>
 *         &lt;element name="AirBrakeSpecialCharacteristic" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}HandBrakeType" minOccurs="0"/>
 *         &lt;element name="HandBrakeBrakedWeight" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="000"/>
 *               &lt;maxInclusive value="999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}NormalLoadingGauge" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonWeightEmpty"/>
 *         &lt;element name="TechnicalRestrictions" type="{http://taf-jsg.info/schemes}Numeric2-2" maxOccurs="6" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "lengthOverBuffers",
        "wagonNumberOfAxles",
        "airBrakeType",
        "brakingPowerVariationDevice",
        "airBrakeSpecialCharacteristic",
        "handBrakeType",
        "handBrakeBrakedWeight",
        "normalLoadingGauge",
        "wagonWeightEmpty",
        "technicalRestrictions"
})
@XmlRootElement(name = "WagonTechData")
public class WagonTechData {

    @XmlElement(name = "LengthOverBuffers")
    protected int lengthOverBuffers;
    @XmlElement(name = "WagonNumberOfAxles")
    protected int wagonNumberOfAxles;
    @XmlElement(name = "AirBrakeType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String airBrakeType;
    @XmlElement(name = "BrakingPowerVariationDevice")
    protected BigInteger brakingPowerVariationDevice;
    @XmlElement(name = "AirBrakeSpecialCharacteristic")
    protected Integer airBrakeSpecialCharacteristic;
    @XmlElement(name = "HandBrakeType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String handBrakeType;
    @XmlElement(name = "HandBrakeBrakedWeight")
    protected Integer handBrakeBrakedWeight;
    @XmlElement(name = "NormalLoadingGauge")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String normalLoadingGauge;
    @XmlElement(name = "WagonWeightEmpty")
    protected int wagonWeightEmpty;
    @XmlElement(name = "TechnicalRestrictions", type = Integer.class)
    protected List<Integer> technicalRestrictions;

    /**
     * Gets the value of the lengthOverBuffers property.
     */
    public int getLengthOverBuffers() {
        return lengthOverBuffers;
    }

    public WagonTechData setLengthOverBuffers(int lengthOverBuffers) {
        this.lengthOverBuffers = lengthOverBuffers;
        return this;
    }

    /**
     * Gets the value of the wagonNumberOfAxles property.
     */
    public int getWagonNumberOfAxles() {
        return wagonNumberOfAxles;
    }

    public WagonTechData setWagonNumberOfAxles(int wagonNumberOfAxles) {
        this.wagonNumberOfAxles = wagonNumberOfAxles;
        return this;
    }

    /**
     * Gets the value of the airBrakeType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAirBrakeType() {
        return airBrakeType;
    }

    public WagonTechData setAirBrakeType(String airBrakeType) {
        this.airBrakeType = airBrakeType;
        return this;
    }

    /**
     * Gets the value of the brakingPowerVariationDevice property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getBrakingPowerVariationDevice() {
        return brakingPowerVariationDevice;
    }

    public WagonTechData setBrakingPowerVariationDevice(BigInteger brakingPowerVariationDevice) {
        this.brakingPowerVariationDevice = brakingPowerVariationDevice;
        return this;
    }

    /**
     * Gets the value of the airBrakeSpecialCharacteristic property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getAirBrakeSpecialCharacteristic() {
        return airBrakeSpecialCharacteristic;
    }

    public WagonTechData setAirBrakeSpecialCharacteristic(Integer airBrakeSpecialCharacteristic) {
        this.airBrakeSpecialCharacteristic = airBrakeSpecialCharacteristic;
        return this;
    }

    /**
     * Gets the value of the handBrakeType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHandBrakeType() {
        return handBrakeType;
    }

    public WagonTechData setHandBrakeType(String handBrakeType) {
        this.handBrakeType = handBrakeType;
        return this;
    }

    /**
     * Gets the value of the handBrakeBrakedWeight property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getHandBrakeBrakedWeight() {
        return handBrakeBrakedWeight;
    }

    public WagonTechData setHandBrakeBrakedWeight(Integer handBrakeBrakedWeight) {
        this.handBrakeBrakedWeight = handBrakeBrakedWeight;
        return this;
    }

    /**
     * Gets the value of the normalLoadingGauge property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNormalLoadingGauge() {
        return normalLoadingGauge;
    }

    public WagonTechData setNormalLoadingGauge(String normalLoadingGauge) {
        this.normalLoadingGauge = normalLoadingGauge;
        return this;
    }

    /**
     * Gets the value of the wagonWeightEmpty property.
     */
    public int getWagonWeightEmpty() {
        return wagonWeightEmpty;
    }

    public WagonTechData setWagonWeightEmpty(int wagonWeightEmpty) {
        this.wagonWeightEmpty = wagonWeightEmpty;
        return this;
    }

    /**
     * Gets the value of the technicalRestrictions property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technicalRestrictions property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnicalRestrictions().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     */
    public List<Integer> getTechnicalRestrictions() {
        if (technicalRestrictions == null) {
            technicalRestrictions = new ArrayList<Integer>();
        }
        return this.technicalRestrictions;
    }

    public WagonTechData setTechnicalRestrictions(List<Integer> technicalRestrictions) {
        this.technicalRestrictions = technicalRestrictions;
        return this;
    }

}
