//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package nl.rls.composer.domain;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import java.math.BigInteger;

@Getter
@Setter
@NoArgsConstructor
@Entity
public class ErrorMessage {
    @Id
    @GeneratedValue
    private Integer id;
    private String messageStatus;
    private BigInteger typeOfError;
    private BigInteger severity;
    private int errorCode;
    private String freeTextField;
    @OneToOne
    private CustomMessageStatus customMessageStatus;
}
