/**
 *
 */
package nl.rls.composer.domain;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;
import java.util.Date;

/**
 * @author berend.wilkens
 *
 */

@NoArgsConstructor
@Getter
@Setter
@MappedSuperclass
public class GenericMessage extends OwnedEntity {
    private Integer messageStatus;
    /**
     * reference used by the sender (e.g.  FTP file name)
     */
    private String senderReference;
    /**
     * Additional information used to route the message to the correct recieving application (if needed)
     */
//    private int messageRoutingID;
    @ManyToOne
    private Company sender;
    @ManyToOne
    private Company recipient;
    /**
     * To indicate the message type transmitted or referred to.
     * 3003        TrainCompositionMessage
     * 9000        ErrorMessage
     */
    private int messageType;

    /**
     * MessageReference part of the message header
     */
    private String messageTypeVersion;
    /**
     * Identification of the Message
     */
    private String messageIdentifier;
    /**
     * Generated by the common Interface
     */
    private Date messageDateTime;
    public GenericMessage(Integer ownerId) {
        super(ownerId);
    }

}
