//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.15 at 11:40:04 PM CET 
//


package nl.rls.ci.soap.dto;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MessageType"/>
 *         &lt;element ref="{}MessageTypeVersion"/>
 *         &lt;element ref="{}MessageIdentifier"/>
 *         &lt;element name="MessageDateTime" type="{}DateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "messageType",
        "messageTypeVersion",
        "messageIdentifier",
        "messageDateTime"
})
@XmlRootElement(name = "MessageReference")
public class MessageReference {

    @XmlElement(name = "MessageType", required = true)
    protected String messageType;
    @XmlElement(name = "MessageTypeVersion", required = true)
    protected String messageTypeVersion;
    @XmlElement(name = "MessageIdentifier", required = true)
    protected String messageIdentifier;
    @XmlElement(name = "MessageDateTime", required = true)
    protected XMLGregorianCalendar messageDateTime;

    /**
     * Gets the value of the messageType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the messageTypeVersion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMessageTypeVersion() {
        return messageTypeVersion;
    }

    /**
     * Sets the value of the messageTypeVersion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMessageTypeVersion(String value) {
        this.messageTypeVersion = value;
    }

    /**
     * Gets the value of the messageIdentifier property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMessageIdentifier() {
        return messageIdentifier;
    }

    /**
     * Sets the value of the messageIdentifier property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMessageIdentifier(String value) {
        this.messageIdentifier = value;
    }

    /**
     * Gets the value of the messageDateTime property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getMessageDateTime() {
        return messageDateTime;
    }

    /**
     * Sets the value of the messageDateTime property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setMessageDateTime(XMLGregorianCalendar value) {
        this.messageDateTime = value;
    }

}
