//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.02 at 11:36:00 AM CEST 
//


package nl.rls.xml.tcm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DerailmentDetectionDeviceEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DerailmentDetectionDeviceEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="EDT 101"/>
 *     &lt;enumeration value="MDV 100"/>
 *     &lt;enumeration value="Non coded device"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DerailmentDetectionDeviceEnumeration")
@XmlEnum
public enum DerailmentDetectionDeviceEnumeration {

    @XmlEnumValue("EDT 101")
    EDT_101("EDT 101"),
    @XmlEnumValue("MDV 100")
    MDV_100("MDV 100"),
    @XmlEnumValue("Non coded device")
    NON_CODED_DEVICE("Non coded device");
    private final String value;

    DerailmentDetectionDeviceEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DerailmentDetectionDeviceEnumeration fromValue(String v) {
        for (DerailmentDetectionDeviceEnumeration c: DerailmentDetectionDeviceEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
