//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.02 at 11:36:00 AM CEST 
//


package nl.rls.xml.tcm;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}MessageHeader"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}MessageStatus"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}AdministrativeContactInformation"/>
 *         &lt;element name="ErrorCauseReference" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}MessageReference"/>
 *                   &lt;element name="MessageSenderReference" type="{http://taf-jsg.info/schemes}FreeText" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Error" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TagReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="TypeOfError">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;enumeration value="0"/>
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Severity">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ErrorCode">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;minInclusive value="1"/>
 *                         &lt;maxInclusive value="9999"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}FreeTextField"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}PlannedTransportIdentifiers" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TransportOperationalIdentifiers" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageHeader",
    "messageStatus",
    "administrativeContactInformation",
    "errorCauseReference",
    "error",
    "plannedTransportIdentifiers",
    "transportOperationalIdentifiers"
})
@XmlRootElement(name = "ErrorMessage")
public class ErrorMessage {

    @XmlElement(name = "MessageHeader", required = true)
    protected MessageHeader messageHeader;
    @XmlElement(name = "MessageStatus", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String messageStatus;
    @XmlElement(name = "AdministrativeContactInformation", required = true)
    protected AdministrativeContactInformation administrativeContactInformation;
    @XmlElement(name = "ErrorCauseReference")
    protected ErrorMessage.ErrorCauseReference errorCauseReference;
    @XmlElement(name = "Error", required = true)
    protected List<ErrorMessage.Error> error;
    @XmlElement(name = "PlannedTransportIdentifiers")
    protected List<CompositIdentifierPlannedType> plannedTransportIdentifiers;
    @XmlElement(name = "TransportOperationalIdentifiers")
    protected List<TransportOperationalIdentifiers> transportOperationalIdentifiers;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeader }
     *     
     */
    public MessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeader }
     *     
     */
    public void setMessageHeader(MessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the messageStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageStatus() {
        return messageStatus;
    }

    /**
     * Sets the value of the messageStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageStatus(String value) {
        this.messageStatus = value;
    }

    /**
     * Gets the value of the administrativeContactInformation property.
     * 
     * @return
     *     possible object is
     *     {@link AdministrativeContactInformation }
     *     
     */
    public AdministrativeContactInformation getAdministrativeContactInformation() {
        return administrativeContactInformation;
    }

    /**
     * Sets the value of the administrativeContactInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdministrativeContactInformation }
     *     
     */
    public void setAdministrativeContactInformation(AdministrativeContactInformation value) {
        this.administrativeContactInformation = value;
    }

    /**
     * Gets the value of the errorCauseReference property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorMessage.ErrorCauseReference }
     *     
     */
    public ErrorMessage.ErrorCauseReference getErrorCauseReference() {
        return errorCauseReference;
    }

    /**
     * Sets the value of the errorCauseReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorMessage.ErrorCauseReference }
     *     
     */
    public void setErrorCauseReference(ErrorMessage.ErrorCauseReference value) {
        this.errorCauseReference = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the error property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorMessage.Error }
     * 
     * 
     */
    public List<ErrorMessage.Error> getError() {
        if (error == null) {
            error = new ArrayList<ErrorMessage.Error>();
        }
        return this.error;
    }

    /**
     * Gets the value of the plannedTransportIdentifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plannedTransportIdentifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlannedTransportIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompositIdentifierPlannedType }
     * 
     * 
     */
    public List<CompositIdentifierPlannedType> getPlannedTransportIdentifiers() {
        if (plannedTransportIdentifiers == null) {
            plannedTransportIdentifiers = new ArrayList<CompositIdentifierPlannedType>();
        }
        return this.plannedTransportIdentifiers;
    }

    /**
     * Gets the value of the transportOperationalIdentifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transportOperationalIdentifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransportOperationalIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransportOperationalIdentifiers }
     * 
     * 
     */
    public List<TransportOperationalIdentifiers> getTransportOperationalIdentifiers() {
        if (transportOperationalIdentifiers == null) {
            transportOperationalIdentifiers = new ArrayList<TransportOperationalIdentifiers>();
        }
        return this.transportOperationalIdentifiers;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TagReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="TypeOfError">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;enumeration value="0"/>
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Severity">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *               &lt;enumeration value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ErrorCode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;minInclusive value="1"/>
     *               &lt;maxInclusive value="9999"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element ref="{http://taf-jsg.info/schemes}FreeTextField"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tagReference",
        "typeOfError",
        "severity",
        "errorCode",
        "freeTextField"
    })
    public static class Error {

        @XmlElement(name = "TagReference")
        protected String tagReference;
        @XmlElement(name = "TypeOfError", required = true)
        protected BigInteger typeOfError;
        @XmlElement(name = "Severity", required = true)
        protected BigInteger severity;
        @XmlElement(name = "ErrorCode")
        protected int errorCode;
        @XmlElement(name = "FreeTextField", required = true)
        protected String freeTextField;

        /**
         * Gets the value of the tagReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTagReference() {
            return tagReference;
        }

        /**
         * Sets the value of the tagReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTagReference(String value) {
            this.tagReference = value;
        }

        /**
         * Gets the value of the typeOfError property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTypeOfError() {
            return typeOfError;
        }

        /**
         * Sets the value of the typeOfError property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTypeOfError(BigInteger value) {
            this.typeOfError = value;
        }

        /**
         * Gets the value of the severity property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSeverity() {
            return severity;
        }

        /**
         * Sets the value of the severity property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSeverity(BigInteger value) {
            this.severity = value;
        }

        /**
         * Gets the value of the errorCode property.
         * 
         */
        public int getErrorCode() {
            return errorCode;
        }

        /**
         * Sets the value of the errorCode property.
         * 
         */
        public void setErrorCode(int value) {
            this.errorCode = value;
        }

        /**
         * Gets the value of the freeTextField property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFreeTextField() {
            return freeTextField;
        }

        /**
         * Sets the value of the freeTextField property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFreeTextField(String value) {
            this.freeTextField = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://taf-jsg.info/schemes}MessageReference"/>
     *         &lt;element name="MessageSenderReference" type="{http://taf-jsg.info/schemes}FreeText" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "messageReference",
        "messageSenderReference"
    })
    public static class ErrorCauseReference {

        @XmlElement(name = "MessageReference", required = true)
        protected MessageReference messageReference;
        @XmlElement(name = "MessageSenderReference")
        protected String messageSenderReference;

        /**
         * Gets the value of the messageReference property.
         * 
         * @return
         *     possible object is
         *     {@link MessageReference }
         *     
         */
        public MessageReference getMessageReference() {
            return messageReference;
        }

        /**
         * Sets the value of the messageReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link MessageReference }
         *     
         */
        public void setMessageReference(MessageReference value) {
            this.messageReference = value;
        }

        /**
         * Gets the value of the messageSenderReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageSenderReference() {
            return messageSenderReference;
        }

        /**
         * Sets the value of the messageSenderReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageSenderReference(String value) {
            this.messageSenderReference = value;
        }

    }

}
