//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.02 at 11:36:00 AM CEST 
//


package nl.rls.xml.tcm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Indication of the Railway or Customer Location
 * 
 * <p>Java class for LocationIdent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationIdent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}CountryCodeISO"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LocationPrimaryCode"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}PrimaryLocationName" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LocationSubsidiaryIdentification" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationIdent", propOrder = {
    "countryCodeISO",
    "locationPrimaryCode",
    "primaryLocationName",
    "locationSubsidiaryIdentification"
})
@XmlSeeAlso({
    nl.rls.xml.tcm.AffectedSection.StartOfSection.class,
    nl.rls.xml.tcm.AffectedSection.EndOfSection.class,
    nl.rls.xml.tcm.TrainInformation.PathPlanningReferenceLocation.class,
    nl.rls.xml.tcm.TrainOrCoachGroupComposition.Unit.ItineraryOfCoachOrTrainset.OriginOfVehicle.class,
    nl.rls.xml.tcm.TrainOrCoachGroupComposition.Unit.ItineraryOfCoachOrTrainset.DestinationOfVehicle.class,
    Station.class,
    PlannedJourneyLocation.class
})
public class LocationIdent {

    @XmlElement(name = "CountryCodeISO", required = true)
    protected String countryCodeISO;
    @XmlElement(name = "LocationPrimaryCode")
    protected int locationPrimaryCode;
    @XmlElement(name = "PrimaryLocationName")
    protected String primaryLocationName;
    @XmlElement(name = "LocationSubsidiaryIdentification")
    protected LocationSubsidiaryIdentification locationSubsidiaryIdentification;

    /**
     * Gets the value of the countryCodeISO property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeISO }
     *     
     */
    public String getCountryCodeISO() {
        return countryCodeISO;
    }

    /**
     * Sets the value of the countryCodeISO property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeISO }
     *     
     */
    public void setCountryCodeISO(String value) {
        this.countryCodeISO = value;
    }

    /**
     * Gets the value of the locationPrimaryCode property.
     * 
     */
    public int getLocationPrimaryCode() {
        return locationPrimaryCode;
    }

    /**
     * Sets the value of the locationPrimaryCode property.
     * 
     */
    public void setLocationPrimaryCode(int value) {
        this.locationPrimaryCode = value;
    }

    /**
     * Gets the value of the primaryLocationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryLocationName() {
        return primaryLocationName;
    }

    /**
     * Sets the value of the primaryLocationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryLocationName(String value) {
        this.primaryLocationName = value;
    }

    /**
     * Gets the value of the locationSubsidiaryIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link LocationSubsidiaryIdentification }
     *     
     */
    public LocationSubsidiaryIdentification getLocationSubsidiaryIdentification() {
        return locationSubsidiaryIdentification;
    }

    /**
     * Sets the value of the locationSubsidiaryIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationSubsidiaryIdentification }
     *     
     */
    public void setLocationSubsidiaryIdentification(LocationSubsidiaryIdentification value) {
        this.locationSubsidiaryIdentification = value;
    }

}
