//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.02 at 11:36:00 AM CEST 
//


package nl.rls.xml.tcm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}PlannedJourneyLocation" maxOccurs="unbounded" minOccurs="2"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}PlannedCalendar"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}RequestedCalendar" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "plannedJourneyLocation",
    "plannedCalendar",
    "requestedCalendar"
})
@XmlRootElement(name = "PathInformation")
public class PathInformation {

    @XmlElement(name = "PlannedJourneyLocation", required = true)
    protected List<PlannedJourneyLocation> plannedJourneyLocation;
    @XmlElement(name = "PlannedCalendar", required = true)
    protected PlannedCalendar plannedCalendar;
    @XmlElement(name = "RequestedCalendar")
    protected RequestedCalendar requestedCalendar;

    /**
     * Gets the value of the plannedJourneyLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plannedJourneyLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlannedJourneyLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlannedJourneyLocation }
     * 
     * 
     */
    public List<PlannedJourneyLocation> getPlannedJourneyLocation() {
        if (plannedJourneyLocation == null) {
            plannedJourneyLocation = new ArrayList<PlannedJourneyLocation>();
        }
        return this.plannedJourneyLocation;
    }

    /**
     * Gets the value of the plannedCalendar property.
     * 
     * @return
     *     possible object is
     *     {@link PlannedCalendar }
     *     
     */
    public PlannedCalendar getPlannedCalendar() {
        return plannedCalendar;
    }

    /**
     * Sets the value of the plannedCalendar property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlannedCalendar }
     *     
     */
    public void setPlannedCalendar(PlannedCalendar value) {
        this.plannedCalendar = value;
    }

    /**
     * Gets the value of the requestedCalendar property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedCalendar }
     *     
     */
    public RequestedCalendar getRequestedCalendar() {
        return requestedCalendar;
    }

    /**
     * Sets the value of the requestedCalendar property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedCalendar }
     *     
     */
    public void setRequestedCalendar(RequestedCalendar value) {
        this.requestedCalendar = value;
    }

}
