//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.02 at 11:36:00 AM CEST 
//


package nl.rls.xml.tcm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RelatedType" type="{http://taf-jsg.info/schemes}MessageCode"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}RelatedIdentifier"/>
 *         &lt;element name="RelatedMessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="RelatedSenderReference" type="{http://taf-jsg.info/schemes}FreeText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "relatedType",
    "relatedIdentifier",
    "relatedMessageDateTime",
    "relatedSenderReference"
})
@XmlRootElement(name = "RelatedReference")
public class RelatedReference {

    @XmlElement(name = "RelatedType")
    protected int relatedType;
    @XmlElement(name = "RelatedIdentifier", required = true)
    protected String relatedIdentifier;
    @XmlElement(name = "RelatedMessageDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar relatedMessageDateTime;
    @XmlElement(name = "RelatedSenderReference", required = true)
    protected String relatedSenderReference;

    /**
     * Gets the value of the relatedType property.
     * 
     */
    public int getRelatedType() {
        return relatedType;
    }

    /**
     * Sets the value of the relatedType property.
     * 
     */
    public void setRelatedType(int value) {
        this.relatedType = value;
    }

    /**
     * Gets the value of the relatedIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedIdentifier() {
        return relatedIdentifier;
    }

    /**
     * Sets the value of the relatedIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedIdentifier(String value) {
        this.relatedIdentifier = value;
    }

    /**
     * Gets the value of the relatedMessageDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRelatedMessageDateTime() {
        return relatedMessageDateTime;
    }

    /**
     * Sets the value of the relatedMessageDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRelatedMessageDateTime(XMLGregorianCalendar value) {
        this.relatedMessageDateTime = value;
    }

    /**
     * Gets the value of the relatedSenderReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedSenderReference() {
        return relatedSenderReference;
    }

    /**
     * Sets the value of the relatedSenderReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedSenderReference(String value) {
        this.relatedSenderReference = value;
    }

}
