//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.02 at 11:36:00 AM CEST 
//


package nl.rls.xml.tcm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}AgainstBooked" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}AgainstReferenced" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "againstBooked",
    "againstReferenced"
})
@XmlRootElement(name = "TrainDelay")
public class TrainDelay {

    @XmlElement(name = "AgainstBooked")
    protected String againstBooked;
    @XmlElement(name = "AgainstReferenced")
    protected String againstReferenced;

    /**
     * Gets the value of the againstBooked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgainstBooked() {
        return againstBooked;
    }

    /**
     * Sets the value of the againstBooked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgainstBooked(String value) {
        this.againstBooked = value;
    }

    /**
     * Delay compared to the referenced Date/Time
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgainstReferenced() {
        return againstReferenced;
    }

    /**
     * Sets the value of the againstReferenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgainstReferenced(String value) {
        this.againstReferenced = value;
    }

}
