INSERT INTO train_activity_type (code, description) VALUES ('0001', 'Commercial stop RU Board/disembark passenger train, load/unload freight train');
INSERT INTO train_activity_type (code, description) VALUES ('0002', 'Operational stop IM Stops needed by the IM (e.g. overpassing by another train)');
INSERT INTO train_activity_type (code, description) VALUES ('0003', 'Service stop RU/IM Stops which are used for non-commercial activities (e.g. boarding of staff)');
INSERT INTO train_activity_type (code, description) VALUES ('0004', 'System stop RU/IM allowing the RU to change a system (e.g. signalling system, safety system)');
INSERT INTO train_activity_type (code, description) VALUES ('0005', 'Reversing stop RU/IM stop to enable train unit to run in the opposite direction (without change of engine)');
INSERT INTO train_activity_type (code, description) VALUES ('0006', 'Stops for reversing move or driver change ends RU stop to enable train unit to run in the opposite direction (with using another engine at the other end of the train and change of driver)');
INSERT INTO train_activity_type (code, description) VALUES ('0007', 'Stops for locomotive to run round train RU stop to enable train unit to run in the opposite direction (with using the same engine at the other end of the train)');
INSERT INTO train_activity_type (code, description) VALUES ('0008', 'Technical check/inspection coaches/wagons RU/IM e.g. at origin or intermediate station: brake test, checking load');
INSERT INTO train_activity_type (code, description) VALUES ('0009', 'Change gauge RU/IM continuation on a network with a different gauge with change of bogies or adaptation of the axles (F->E, SVE->FI)');
INSERT INTO train_activity_type (code, description) VALUES ('0010', 'attach engine/unit RU Unit not previously in service');
INSERT INTO train_activity_type (code, description) VALUES ('0011', 'detach engine/unit RU Unit no longer in service');
INSERT INTO train_activity_type (code, description) VALUES ('0012', 'change engine RU ');
INSERT INTO train_activity_type (code, description) VALUES ('0013', 'attach coach/wagon RU ');
INSERT INTO train_activity_type (code, description) VALUES ('0014', 'detach coach/wagon RU ');
INSERT INTO train_activity_type (code, description) VALUES ('0015', 'attach and detach coach/wagon RU ');
INSERT INTO train_activity_type (code, description) VALUES ('0016', 'attach train  Operational Train (in service)');
INSERT INTO train_activity_type (code, description) VALUES ('0017', 'split train  Operational Train (in service)');
INSERT INTO train_activity_type (code, description) VALUES ('0018', 'Parking of vehicle RU e.g. need to park the train/composition midway for several hours');
INSERT INTO train_activity_type (code, description) VALUES ('0019', 'Mail/parcel services RU ');
INSERT INTO train_activity_type (code, description) VALUES ('0020', 'shunting RU actual activity of shunting');
INSERT INTO train_activity_type (code, description) VALUES ('0021', 'shunting service RU Request for shunting service (if offered by the IM or a third party)');
INSERT INTO train_activity_type (code, description) VALUES ('0022', 'Terminal service (terminal in the meaning of final destination) RU Request for services at the end of a train run (if offered by the IM or a third party)');
INSERT INTO train_activity_type (code, description) VALUES ('0023', 'Loco driver change RU ');
INSERT INTO train_activity_type (code, description) VALUES ('0024', 'Loco driver break RU legal issue, e.g. to respect working law');
INSERT INTO train_activity_type (code, description) VALUES ('0025', 'Crew change RU different to loco driver change as for the change of the crew a platform will be needed');
INSERT INTO train_activity_type (code, description) VALUES ('0026', 'Custom and passport facilities RU ');
INSERT INTO train_activity_type (code, description) VALUES ('0027', 'Other stop reason (miscellaneous) RU/IM ');
INSERT INTO train_activity_type (code, description) VALUES ('0028', 'Boarding only RU ');
INSERT INTO train_activity_type (code, description) VALUES ('0029', 'Disembarking only RU ');
INSERT INTO train_activity_type (code, description) VALUES ('0030', 'Stop on request RU ');
INSERT INTO train_activity_type (code, description) VALUES ('0031', 'Departure equals to arrival time RU If in some stations only arrival times are published, this activity code may used to indicate that the train cannot continue before the published arrival time in case of an early arrival.');
INSERT INTO train_activity_type (code, description) VALUES ('0032', 'Departure after disembarking RU mainly used at the end of train run, train may continue as soon as all passengers have disembarked');
INSERT INTO train_activity_type (code, description) VALUES ('0033', 'No waiting for connection RU ');
INSERT INTO train_activity_type (code, description) VALUES ('0034', 'Watering RU Indicates the IM that a track with water access will be needed.');
INSERT INTO train_activity_type (code, description) VALUES ('0035', 'Heating  Indicates the IM that a track with heating equipment will be needed.');
INSERT INTO train_activity_type (code, description) VALUES ('0036', 'Cleaning / disinfecting RU');
INSERT INTO train_activity_type (code, description) VALUES ('0037', 'Treatment on plants and live animals RU Watering, Foddering, Milking, Spraying, Closing ventilation flaps, Opening ventilation flaps');
INSERT INTO train_activity_type (code, description) VALUES ('0038', 'Treatment of perishable goods RU Checking the temperature, Re-icing, Heating, Checking the proper functioning of the mechanical refrigeration equipment, Refuelling machinery, Switching machinery on or off');
INSERT INTO train_activity_type (code, description) VALUES ('0039', 'Administrative operations RU Weighing, Re-forwarding, Submission to phytosanitary inspections');
INSERT INTO train_activity_type (code, description) VALUES ('0040', 'Run Through (Passing Time) IM');
INSERT INTO train_activity_type (code, description) VALUES ('0041', 'Photo run-by / Photo-stop ');
INSERT INTO train_activity_type (code, description) VALUES ('0042', 'Train Waiting Waiting according to local rules');
INSERT INTO train_activity_type (code, description) VALUES ('0043', 'Train running with another train RU Where trains have been attached at a previous location on the schedule');
INSERT INTO train_activity_type (code, description) VALUES ('0044', 'Next working service RU Association where there is a need to define a relationship between a train and its next service. The same vehicle is used for the next train service. Also called "train-set turnover"');
INSERT INTO train_activity_type (code, description) VALUES ('0045', 'Previous working service RU Association where there is a need to define a relationship between a train and its previous service. The same vehicle is reused from the previous train service.');
INSERT INTO train_activity_type (code, description) VALUES ('0046', 'Connecting service to other train. ');
INSERT INTO train_activity_type (code, description) VALUES ('0047', 'Connecting service from other train.');