package nl.rls.composer.domain.message;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.Date;

/**
 * @author berend.wilkens
 * This element identifies the message
 */
@ToString
@NoArgsConstructor
@Getter
@Setter
public class MessageReference {
    private int id;
    /**
     * To indicate the message type transmitted or referred to.
     * 3003        TrainCompositionMessage
     * 9000        ErrorMessage
     */
    private int messageType;
    private String messageTypeVersion;
    /**
     * Identification of the Message
     */
    private String messageIdentifier;
    /**
     * Generated by the common Interface
     */
    private Date messageDateTime;
}
